### ISSUE TITLE
Access without www

### ISSUE THREAD

**Issue by edent** [nhsx/old-nhsx-website#16]
https://nhsx.nhs.uk/ doesn't resolve. Please can we add that?

**Comment by theonlymojo** [comment]
Yes - waiting on the DNS team to update the records. Will update once resolving.

**Comment by chrimesdev** [comment]
Looks like the domain now resolves.

**Comment by edent** [comment]
My DNS checks aren't showing it yet. Will keep an eye on it.

**Comment by chrimesdev** [comment]
This has been escalated internally. The domain resolves on the office network but not on my 4g/home network.

**Comment by edent** [comment]
Looks like it is working now. Thanks all!
