### ISSUE TITLE
Preconnect to https://assets.nhs.uk/ not required

### ISSUE THREAD

**Issue by Nooshu** [nhsx/old-nhsx-website#9]
Excellent work NHSX Team. Small observation below:

The preconnect in the head to the assets domain isn't required.

```html
<link type="font/woff2" href="https://assets.nhs.uk/fonts/FrutigerLTW01-55Roman.woff2" rel="preload" as="font" crossorigin>
<link type="font/woff2" href="https://assets.nhs.uk/fonts/FrutigerLTW01-65Bold.woff2" rel="preload" as="font" crossorigin>
<link href="https://www.nhs.uk/" rel="preconnect  dns-prefetch">
<link href="https://assets.nhs.uk/" rel="preconnect  dns-prefetch" crossorigin>
```

By the time the browser parses the assets `preconnect` the connection has already been negotiated by the font `preload`. You could bump the assets `preconnect` up the source order or even send it as a [link header](https://www.w3.org/TR/resource-hints/#fetching-the-resource-hint-link).

Also `preconnect  dns-prefetch` aren't both required. `preconnect` includes DNS lookup, TCP handshake, and optional TLS negotiation. So you could drop it down to only `preconnect`

**Comment by chrimesdev** [comment]
Great spot, thanks Matt @Nooshu!

I've reordered the `preconnect` and removed the unneeded`dns-prefetch`. How does this look to you? [View the commit on the develop branch](https://github.com/nhsx/nhsx-website/commit/83d042068e1fd05a453ac921f7d00bf6f2397b95)

Looks like its something we'll need to fix on the NHS.UK frontend library too, I will raise an issue there and do some further reading - never knew that was the case with preconnect.

**Comment by Nooshu** [comment]
Yes, that looks good @AdamChrimes 👍

**Comment by chrimesdev** [comment]
Thanks @Nooshu will get it released within the next few days.

**Comment by Nooshu** [comment]
Quick update on this. It's worth keeping an eye on this [Twitter thread](https://twitter.com/AndyDavies/status/1115652039328006145). All major browsers support [dns-prefetch](https://beta.caniuse.com/#feat=link-rel-dns-prefetch) and [preconnect](https://beta.caniuse.com/#feat=link-rel-preconnect), but the thread suggests there may be edge-cases where having both listed can help. These are unconfirmed though.

**Comment by chrimesdev** [comment]
I believe the initial advice to do this, the way we did, came from @csswizardry during a performance workshop.

Looks like the same implementation on Harry’s website https://csswizardry.com/

Harry, do you know the reason for using both?
